language: julia
os:
    - linux
    - osx
julia:
    - 0.6
notifications:
    email: false
sudo: false
dist: trusty
addons:
    apt:
        packages:
            - libcfitsio3-dev
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("LibHealpix")'
    - julia --check-bounds=yes -e 'Pkg.test("LibHealpix"; coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("LibHealpix")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
    - julia -e 'cd(Pkg.dir("LibHealpix")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'

